import Head from 'next/head';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Devlog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>안녕하세요 Devlog 입니다</main>
    </div>
  );
}
